name: template
description: A flutter project template with theme, state management, utils and folder structure.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  hooks_riverpod: ^2.4.3
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  auto_route: ^7.8.4
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.0
  sembast: ^3.5.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ionicons: ^0.2.2
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  flutter_logs: ^2.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  flutter_flavorizr: ^2.2.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar_female.jpg
    - assets/images/avatar_male.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flavoring
flavors:
  prod:
    app:
      name: "Flutter Template"

    android:
      applicationId: "dev.mixin27.template"  
    ios:
      bundleId: "dev.mixin27.template"
    macos:
      bundleId: "dev.mixin27.template"  
  stg:
    app:
      name: "[STG] Flutter Template"
  
    android:
      applicationId: "dev.mixin27.template.stg"
    ios:
      bundleId: "dev.mixin27.template.stg"
    macos:
      bundleId: "dev.mixin27.template.stg"
  dev:
    app:
      name: "[DEV] Flutter Template"
  
    android:
      applicationId: "dev.mixin27.template.dev"
    ios:
      bundleId: "dev.mixin27.template.dev"
    macos:
      bundleId: "dev.mixin27.template.dev"