name: template
description: A flutter project template with theme, state management, utils and folder structure.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  envied: ^0.3.0+3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  equatable: ^2.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.3
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar_female.jpg
    - assets/images/avatar_male.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flavoring
flavors:
  prod:
    app:
      name: "Ecommerce"

    android:
      applicationId: "com.yangonyinxaing.ecommerce"  
    ios:
      bundleId: "com.yangonyinxaing.ecommerce"
    macos:
      bundleId: "com.yangonyinxaing.ecommerce"  
  stg:
    app:
      name: "[STG] Ecommerce"
  
    android:
      applicationId: "com.yangonyinxaing.ecommerce.stg"
    ios:
      bundleId: "com.yangonyinxaing.ecommerce.stg"
    macos:
      bundleId: "com.yangonyinxaing.ecommerce.stg"
  dev:
    app:
      name: "[DEV] Ecommerce"
  
    android:
      applicationId: "com.yangonyinxaing.ecommerce.dev"
    ios:
      bundleId: "com.yangonyinxaing.ecommerce.dev"
    macos:
      bundleId: "com.yangonyinxaing.ecommerce.dev"